# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestGuardadoincompleto():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_guardadoincompleto(self):
    self.driver.get("https://tucan.toolsincloud.net/")
    self.driver.find_element(By.CSS_SELECTOR, ".grid-sidebar:nth-child(7) img").click()
    self.driver.find_element(By.CSS_SELECTOR, ".home-edit-button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".modal-body").click()
    self.driver.find_element(By.ID, "exampleInputEmail1").click()
    self.driver.find_element(By.NAME, "update").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".text-center:nth-child(1)").text == "name is required"
    self.driver.find_element(By.NAME, "update").click()
    self.driver.find_element(By.CSS_SELECTOR, ".fa-sign-out-alt").click()
  
